########################################
# Basic Configuration
########################################

# main menu navigation
# for more icon information, please visit https://github.com/D-Sketon/hexo-theme-reimu/issues/30
menu:
  - name: home
    url: ""
    icon: # default use taichi icon, you can use a hexadecimal representation of fontawesome or icon_font, like 'f0c1'
  - name: archives
    url: "archives"
    icon:
  - name: about
    url: "about"
    icon:
  - name: friend
    url: "friend"
    icon:

mainSections: ["post"]
# 年，月，日及时间的格式化样式
# Format style for year,month,date & time
yearFormat: "2006"
monthFormat: "2006-01"
dateFormat: "2006-01-02"
timeFormat: "2006-01-02 15:04:05"

author: 新人类 # 应该改为你的名字
description: "致敬勇于探索未知的人类！"  # 可以改为你的个人描述
subtitle: "新人类"  # 可以改为你的个人副标题

banner: "images/飞船1.jpeg"  # 确保这个图片文件存在
# 删除这一行，避免重复设置
# avatar: "https://s21.ax1x.com/2025/03/21/pE0C2Xq.jpg"  # 确保这个头像文件存在
# You can also write it in the form of the following url
# banner: "https://example.com"

# If you want to use the srcset attribute, please enable it
banner_srcset:
  enable: false
  srcset:
    - src: "images/78ac40f951241471287ff985bc25b24b2f03a241.jpg"
      media: "(min-width: 800px)"
    - src: "images/banner-600w.webp"
      media: "(max-width: 479px)"
    - src: "images/banner-800w.webp"
      media: "(max-width: 799px)"
    - src: "images/banner.webp"
      media: "(min-width: 800px)"

# 修改为正确的路径，确保以/开头
avatar: "images/78ac40f951241471287ff985bc25b24b2f03a241.jpg"
# Control the display of the post cover
# If not set, the banner image will be displayed by default
# Its priority is lower than the cover in the Front-matter
cover: rgb(117,117,255)  # 从红色系改为蓝色系

# Control the display of the post toc
# Its priority is lower than the toc in the Front-matter
toc: true

# Open Graph
open_graph:
  enable: true
  options:
    #twitter_card: <twitter:card>
    #twitter_id: <twitter:creator>
    #twitter_site: <twitter:site>
    #twitter_image: <twitter:image>
    #google_plus: <g+:profile_link>
    #fb_admins: <fb:admin_id>
    #fb_app_id: <fb:app_id>

# Content
excerpt_link: Read More

# Inject code snippet
# Make sure your code snippet is safeHTML
injector:
  head_end: |
    <style>
      :root {
        --theme-color: #3366cc;         /* 更深的蓝色 */
        --theme-color-light: #99ccff;   /* 更亮的蓝色 */
        --theme-color-dark: #003399;    /* 更暗的蓝色 */
        --theme-color-text: #ffffff;    /* 按钮文字颜色 */
      }
      
      /* 移除蓝色滤镜，因为新图片已经是蓝色调 */
      /* .banner {
        filter: hue-rotate(240deg) saturate(1.2) !important;
      } */
      
      /* 导航栏背景颜色 */
      .header-inner {
        background-color: var(--theme-color) !important;
      }
      
      /* 导航菜单项文字颜色 */
      .menu-item a {
        color: white !important;
      }
      
      /* 导航菜单图标颜色 */
      .menu-item svg, .menu-item i {
        color: #000000 !important; /* 改为黑色 */
        fill: #000000 !important;
      }
      
      /* 文章标题和按钮颜色 */
      .article-title a, .post-title, h1, h2, h3, h4, h5, h6 {
        color: var(--theme-color-dark) !important;
      }
      
      /* 增强"新人类"副标题的样式 */
      .subtitle {
        color: #0033cc !important;
        font-weight: 700 !important;
        text-shadow: 0 0 3px rgba(255, 255, 255, 0.7) !important;
        font-size: 1.3em !important;
        letter-spacing: 1px !important;
      }
      
      /* 右侧作者信息卡片标题 */
      .author-info .author-title, .sidebar-title {
        color: var(--theme-color-dark) !important;
        font-weight: bold !important;
      }
      
      /* 右侧作者信息卡片背景和边框 */
      .author-info {
        background-color: rgba(153, 204, 255, 0.1) !important;
        border-color: var(--theme-color) !important;
        border-width: 2px !important;
      }
      
      /* 头像样式 */
      .author-info img.avatar {
        display: block !important;
        width: 120px !important;
        height: 120px !important;
        border-radius: 50% !important;
        border: 3px solid var(--theme-color) !important;
        margin: 0 auto 10px !important;
        box-shadow: 0 0 10px rgba(0, 51, 153, 0.3) !important;
      }
      
      /* 标签和分类按钮背景 */
      .tag-item, .category-item, .friend-item, .recent-post-item {
        background-color: transparent !important; /* 设置为透明 */
        color: inherit !important; /* 恢复默认文字颜色 */
      }
      
      /* 侧边栏标题 */
      .sidebar-title, .widget-title, .archive-title {
        color: var(--theme-color-dark) !important;
      }
      
      /* 文章卡片边框和阴影 */
      .post-card {
        border-color: var(--theme-color-light) !important;
        box-shadow: 0 2px 8px rgba(0, 51, 153, 0.1) !important;
      }
      
      /* 按钮和链接高亮 */
      .button, .btn, button, input[type="button"], input[type="submit"], .pagination-item.current {
        background-color: var(--theme-color) !important;
        color: var(--theme-color-text) !important;
      }
      
      /* 链接颜色 */
      a {
        color: var(--theme-color-dark) !important;
      }
      
      a:hover {
        color: var(--theme-color) !important;
      }
      
      /* 文章元信息 */
      .article-meta, .article-footer {
        color: var(--theme-color-dark) !important;
      }
      
      /* 搜索框 */
      .search-form {
        border-color: var(--theme-color) !important;
      }
      
      /* 页脚 */
      .footer {
        background-color: var(--theme-color-light) !important;
        color: var(--theme-color-dark) !important;
      }
      
      /* Hello World 标题 */
      .post-title a {
        color: var(--theme-color-dark) !important;
      }
    </style>
  head_begin: # Inject code snippet right after <head>
  body_begin: # Inject code snippet right after <body>
  body_end: # Inject code snippet right before </body>
  sidebar_begin: # Inject code snippet right after <aside>
  sidebar_end: # Inject code snippet right before </aside>

# Footer copyright
# Inject code snippet right in the footer copyright
# Make sure your code snippet is safeHTML
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# copyright: |-
#   <div style="flex-direction:column;align-items: center;"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></div>

footer:
  since: 2020 # 2020-current year
  powered: true
  count: true
  busuanzi: true
  icon:
    url: "../images/taichi.png" # this path is relative to the css/main.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask

# Sidebar
sidebar: right

social:
  # email: mailto:xxx@gmail.com
  github: https://github.com/bluespace3
  # 其他社交媒体...
  # google: https://plus.google.com/yourname
  # twitter: https://twitter.com/yourname
  # facebook: https://www.facebook.com/yourname
  # instagram: https://www.instagram.com/yourname
  # linkedin: https://www.linkedin.com/in/yourname
  # pinterest: https://www.pinterest.com/yourname
  # youtube: https://www.youtube.com/channel/yourname
  # vimeo: https://vimeo.com/yourname
  # flickr: https://www.flickr.com/photos/yourname
  # dribbble: https://dribbble.com/yourname
  # behance: https://www.behance.net/yourname
  # bilibili: https://space.bilibili.com/yourname
  # weibo: https://weibo.com/yourname
  # zhihu: https://www.zhihu.com/people/yourname
  # reddit: https://www.reddit.com/user/yourname
  # tumblr: https://yourname.tumblr.com
  # medium: https://medium.com/@yourname
  # deviantart: https://yourname.deviantart.com
  # stackoverflow: https://stackoverflow.com/users/yourname
  # keybase: https://keybase.io/yourname
  # telegram: https://t.me/yourname
  # discord: https://discordapp.com/users/yourname
  # steam: https://steamcommunity.com/id/yourname

widgets:
  - category
  - tag
  - tagcloud
  - recent_posts

# Widget behavior
category_limits: 10
tag_limits: 10
recent_posts_limits: 5
tagcloud_limits: 20

# Archive behavior
only_show_capsule_in_index: false # If you have hugo amounts of tags and categories, you can set this to true to only show the capsule in the index page for better performance

########################################
# CSS
########################################

anchor_icon: # default use '#' icon, you can use a hexadecimal representation of fontawesome or icon_font, like 'f0c1'

reimu_cursor:
  enable: true
  cursor:
    default: ../images/cursor/reimu-cursor-default.png  # this path is relative to the css/main.css, so it needs to go up one level to reach the images folder
    pointer: ../images/cursor/reimu-cursor-pointer.png
    text: ../images/cursor/reimu-cursor-text.png

icon_font: 4552607_0khxww3tj3q9

# https://fonts.google.com/
# Google Fonts, higher priority than local_font
font:
  article:
    - Mulish
    - Noto Serif SC
  code:
    # - Ubuntu Mono
    # - Source Code Pro
    # - JetBrains Mono

# Local FallBack Font
local_font:
  article:
    - "-apple-system"
    - PingFang SC
    - Microsoft YaHei
    - sans-serif
  code:
    - Menlo
    - Monaco
    - Consolas
    - monospace

dark_mode:
  # true means that the dark mode is enabled by default
  # false means that the dark mode is disabled by default
  # auto means that the dark mode is automatically switched according to the system settings
  enable: auto # true | false | auto

########################################
# Analytics
########################################

baidu_analytics: false
google_analytics: false
clarity: false

########################################
# Markdown Display
########################################

code_block:
  # whether to expand the code block by default
  # true means expand all code blocks by default
  # false means collapse all code blocks by default
  # number means collapse the code block by default when the number of lines exceeds the specified value
  expand: true

math:
  katex:
    enable: true
  mathjax:
    enable: false
    options: # see https://docs.mathjax.org/en/latest/web/configuration.html
    # we need to put the configuration in an array, because hugo will automatically convert the key to lowercase
      [
        {
          tex:
            {
              tags: "ams",
              useLabelIds: true,
              inlineMath: [["$", "$"], ['\\(', '\\)']],
              displayMath: [["$$", "$$"], ['\\[', '\\]']],
              processEscapes: true,
              processEnvironments: true,
              autoload: { color: [], colorv2: ["color"] },
              packages: { "[+]": ["noerrors"] },
            },
          options:
            {
              skipHtmlTags:
                ["script", "noscript", "style", "textarea", "pre", "code"],
              ignoreHtmlClass: "tex2jax_ignore",
              processHtmlClass: "tex2jax_process",
            },
          loader: { load: ["input/asciimath", "[tex]/noerrors"] },
        },
      ]

########################################
# Comment system
########################################

# valine comment system. https://valine.js.org
# version 1.5.1
# notify and verify have been deprecated
valine:
  enable: false # if you want to use valine,please set this value is true
  appId: # leancloud application app id
  appKey: # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: mp # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
  recordIP: true # whether to record the IP address of the commenters
  highlight: true # whether to highlight the code blocks
  visitor: false # whether to display the number of visitors

# https://waline.js.org/
waline:
  enable: false
  serverURL:
  lang: zh-CN
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/weibo
    - https://unpkg.com/@waline/emojis@1.2.0/alus
    - https://unpkg.com/@waline/emojis@1.2.0/bilibili
    - https://unpkg.com/@waline/emojis@1.2.0/qq
    - https://unpkg.com/@waline/emojis@1.2.0/tieba
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
    - mail
  wordLimit: 0
  pageSize: 10
  pageview: true

# https://twikoo.js.org
twikoo:
  enable: false
  envId: # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  region:

# https://github.com/gitalk/gitalk/blob/master/readme-cn.md
gitalk:
  enable: false
  clientID:
  clientSecret:
  repo:
  owner:
  admin:
  md5: false

# https://giscus.app/zh-CN
giscus:
  enable: true
  repo: bluespace3/bluespace3.github.io
  repoId: R_kgDOOLQbCg
  category: Announcements
  categoryId: DIC_kwDOOLQbCs4Cojds
  mapping: pathname
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 0
  inputPosition: bottom
  # commentTheme: preferred_color_scheme invalid
  lang: zh-CN

########################################
# Search
########################################

algolia_search:
  enable: true
  appID: XOD7QMRN6A
  apiKey: f0c206edfe24bfd2fe1b5837560b4b5e
  indexName: bluespace3_github_io_xod7qmrn6a_pages
  hits:
    per_page: 10
  labels:
    input_placeholder: "搜索....."
    hits_empty: "未发现与 「${query}」相关内容"
    hits_stats: "找到${hits}条结果（用时 ${time} ms）"

########################################
# Animation
########################################

preloader:
  enable: true
  text: 蓝色空间号启动中...
  icon: # default use inline svg for fast speed, you can use a image url, like '/images/taichi.png'

# see https://github.com/D-Sketon/aos.js
animation:
  enable: true
  options:
    header:
      title: slide-up
      subTitle: slide-down
    home:
      post: fade-up
      widget: fade-up
      sidebar: fade-up
    article:
      whole: fade-up
      date: zoom-in
      category: zoom-in
      tag: zoom-in
      comment: zoom-in
      reading: zoom-in
      nav: fade-up
    archive:
      whole: fade-up
      tag: zoom-in
      category: zoom-in
      section: fade-up
      nav: fade-up

# see https://github.com/D-Sketon/mouse-firework
firework:
  enable: true
  options:
    excludeElements: ["a", "button"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors: ["#5252ff", "#7c7cff", "#afafff", "#d0d0ff"]  # 从红色系改为蓝色系
        number: 20
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
          alpha: [0.3, 0.5]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["#0000ff"]  # 从红色改为蓝色
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: [0.2, 0.5]
          lineWidth: 6

########################################
# Extended features
########################################

# show the copyright below each article
article_copyright:
  enable: false
  content:
    author: true
    link: true
    title: false
    date: false
    updated: false
    license: true

# Clipboard configuration
clipboard:
  success: 复制成功(*^▽^*)
  fail: 复制失败 (ﾟ⊿ﾟ)ﾂ
  copyright:
    enable: false
    count: 50 # The number of characters when the copyright is displayed
    content: 本文版权：本博客所有文章除特别声明外，均采用 BY-NC-SA 许可协议。转载请注明出处！

# Back To Top
top:
  enable: true
  position: right # left or right
  icon:
    url: "../images/taichi.png" # this path is relative to the css/main.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask

# whether to display the notification when the article is outdated
outdate:
  enable: false
  daysAgo: 180 # The number of days after which the article is considered outdated
  message: 本文最后更新于 {time}，请注意文中内容可能已经发生变化。

# ICP 备案
icp:
  icpnumber: # ICP备案号
  beian: # 网安备案号
  recordcode: # 网安备案链接中的recordcode参数

# Sponsor
sponsor:
  enable: false
  tip: 请作者喝杯咖啡吧！
  icon:
    url: "../images/taichi.png" # this path is relative to the css/main.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask
  qr:
    # - name: 支付宝
    #   src: "sponsor/alipay.jpg"
    # - name: 微信
    #   src: "sponsor/wechat.png"

# Share
share:
  # - facebook
  # - twitter
  # - linkedin
  # - reddit
  # - weibo
  # - qq
  # - weixin

# show categories card on home page
home_categories:
  enable: true
  content:
    - categories: # string (single-layer category) or array (multi-layer category)
      cover: rgb(117,117,255)
    - categories:
      cover: rgb(117,117,255)

########################################
# Experimental features
########################################

# Experimental, may have a lot of bugs, open with caution!
pjax:
  enable: false

# Experimental
# https://github.com/GoogleChromeLabs/quicklink
quicklink:
  enable: false
  # The `requestIdleCallback` timeout, in milliseconds.
  timeout: 3000
  # Whether or not the URLs within the options.el container should be treated as high priority.
  # When true, quicklink will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true
  # Determine if a URL should be prefetched.
  # Only support string
  ignores: []

# Experimental
service_worker:
  enable: false

# Experimental
live2d:
  enable: false
  position: left # left or right

# Experimental
live2d_widgets:
  enable: false
  position: left # left or right

# https://github.com/CodeByZach/pace
pace:
  enable: true

# Experimental
# Please turn on pjax to use this feature
player:
  # if you enable meting, you must enable aplayer first
  aplayer:
    enable: true  # 启用 APlayer 播放器
    options:
      audio:
        - name: "Free Compress"  # 音乐名称
          artist: "Unknown Artist"  # 艺术家名称
          url: "/freecompress-2906303867.mp3"  # 音频文件路径，确保以 / 开头
          cover: ""  # 可选，封面图片路径
      fixed: true  # 固定在页面底部
      autoplay: false  # 是否自动播放
      loop: all  # 循环模式，可选值：'all', 'one', 'none'
      order: list  # 播放顺序，可选值：'list', 'random'
      preload: auto  # 预加载模式，可选值：'none', 'metadata', 'auto'
      volume: 0.7  # 默认音量，范围 0~1
      mutex: true  # 是否阻止多个播放器同时播放
      listFolded: false  # 播放列表是否折叠
      lrcType: 0  # 歌词类型，0 表示无歌词
  meting:
    # https://github.com/metowolf/MetingJS
    # if you want to use meting, please enable aplayer first
    enable: false
    meting_api: # custom api
    options:
      id: 2265921590
      server: netease
      type: playlist
      auto:

########################################
# pangu.js
########################################

pangu:
  # more information: https://github.com/vinta/pangu.js 
  enable: false  # enable pangu.js to add space between Chinese and English

algolia_search.enable: true